# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAplikasi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestAplikasi
  pod 'Alamofire'
  pod 'StepSlider'
  pod 'lottie-ios'
  pod 'RxSwift', '6.6.0'
  pod 'RxCocoa', '6.6.0'
  pod 'Alamofire'
  pod 'RxAlamofire'

  target 'TestAplikasiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestAplikasiUITests' do
    # Pods for testing
  end

end
