# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectPertama' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectPertama
  pod 'Alamofire', '5.8.1'
  pod 'netfox'
  pod 'RxSwift', '6.6.0'
  pod 'RxCocoa', '6.6.0'
  pod 'SnapKit', '~> 5.6'
  pod 'SkeletonView'
  pod 'FloatingPanel'
  pod 'lottie-ios'

end
